# Generated by Django 5.2 on 2025-04-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
