# Generated by Django 5.2 on 2025-04-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/chat/group_images'),
        ),
    ]
