# Generated by Django 5.2 on 2025-04-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0002_alter_chatroom_group_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypingStatus',
        ),
    ]
